name: A workflow to sync master with changes in fork repo
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    name: sync-master-fork 
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./cmd
      env:
        USER_NAME: "<your-username>"
        PASSWORD: "<your-password>"
